---
sudo: required
language: python
python: 2.7
cache: pip

env:
  - ANSIBLE=2.5
  - ANSIBLE=2.6
  - ANSIBLE=2.7

services:
  - docker

install:
  - pip install ansible=="$ANSIBLE*" molecule docker

script:
  - molecule test
