---
- name: Check if www.conf is ansible managed
  lineinfile:
    path: '{{ php_fpm_config_path }}/pool.d/www.conf'
    regexp: '^; ansible managed$'
    state: absent
  check_mode: true
  register: pool

- name: Remove default pool
  file:
    path: '{{ php_fpm_config_path }}/pool.d/www.conf'
    state: absent
  when: pool is not changed

- name: Configure pools
  template:
    src: pool.conf.j2
    dest: '{{ php_fpm_config_path }}/pool.d/{{ item.name }}.conf'
  loop: '{{ php_fpm_pools }}'
  notify: Restart php-fpm
